travis:
  secure:
    BINSTAR_TOKEN: C6+9wENFMDSUT7Nps3QlO6AwvsU6MzxLYcK2OQ1I7PSKbMvqMI82ar/IY5Z1QBi+lIA0D+rMT7QWaX4hfoTjxEDoNasbKZ6yFqzAr2cQlj68BLUbtv58qFxEw1L6xM7mfSqcq0P185iGkYIrEpaTDwR28ozCfEMxygrU5aclU2OjiaNlixrYFF5bWmfhsDPmtnPIv+VDYYRCdpRUsL0OZLhdT9Ty5OCNU6Li8o9evn5sVCmeIj2BIv2wZ0yun36POf9NcqN2KRi8FHlpFczUsa+ZWg/tadsqKZFySp/v18GeWqTiAtQjvKHJ5uikawP3oKTWZw6Ijaj/W9yOIF5yX0iXsqJUyEktM2ax2VILpApfW89AO9icnAwkyMfbrYBbhQanCVlGg0X45ptpq6idC7TKec7nNnZgmrvD3dvMMLSuWWsKHdW0g5Vvzkrw37JcgtobDxnnluVDRUebVO50eNJiUHlkoe44uHuBpeDMHufhGyDZDAeBlq5gdg8M9aK/zawp7b7aKvW+m4bRxp+f9yb3sE5TZEPKPwbXsVIvKX1pBO2WYYTAy7RhOlNsCXI1HPA74cf0ECM2hp0l0McB4ehH7bd1DlmszoOeWVPXz80KJy/SGfguHgXPxwL/MSnwGq10g0trQfyATsOw/LwDVUbLTI6kULI/sM4mR0noOqM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
