travis:
  secure:
    BINSTAR_TOKEN: XjBy1+EdvaTViZ9on9uF77kspf1vJxTgg6mpTQTkDqj+wIXkjJWYEVUmNZCU58Qh3/0oDV3vVGtFYf5bGg7c1Tyf7QLoWkbTsAVY6UvsbOLjcRLUUvI5oFV6W8+/rUvJQK946BMHcv1Wp/PJOuQPmkvH/L4NzsWBMZT5sAaD1MXiykgcgMOQAjXqS244LoISUNBnAU4wxOa+PVQvEQIo3aIB+XutzKgf9Iub1eoBI8FCSj2KK/daJsqynKetvGLdrWstBraDidr6/Rvf6KjRvclnsl+/jma20/sdz0VxBDq59qVgsToSrwF4bKGdH3/w27RXCf2z7MnYsD4w3lYHq4giT5XIvScOyqRkFxhwAENn4FVi7sRxX4/x1g7cVDjExIcdDq9qvcSlBoGCt79DyMTemvfBB5L92dspQjwD7tZ36W3WyXWD4JofV+tg8ORH1L5iA5L5lyzFARmfkNnD+/sw9OL8r2SUriCDiMATG2GRchE8FBOe4HPR/JGE9tpLEg5Ux57t63gbErZsg9fnFtpWAemlQDCfymQKaHNNsH5j0+wIMmxddDGYqgm5ft/8wqZNzxnl6S5/iEWsm9JfcfxmiD5QfSQwI/kgldR0gXfBD5MrK7mO6CM1f627LiK+IaARiFOih53VEj8Bq3BJ/KVYAwapyky/ixy01hQ56cA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
